#!/usr/bin/env python3
# Host-side converter: dino.png + cactus.png -> sprites.py (MicroPython).
#
# Reads user-supplied PNGs in the project root, downsamples each with
# LANCZOS, thresholds to monochrome, packs into MONO_HLSB bytes, and
# emits sprites.py with per-sprite dimensions.
#
# dino.png produces two run frames (frame B is derived from frame A by
# lifting the trailing leg one row for a stride animation).
# cactus.png produces two obstacle sizes (small + large) from the same
# input by downsampling to different heights.
#
# Run whenever any source PNG changes:
#   python3 tools/build_sprites.py
#
# The resulting sprites.py must be copied to the Pico alongside main.py
# and sh1107.py.

from pathlib import Path
import sys

try:
    from PIL import Image
except ImportError:
    sys.exit("PIL/Pillow required — install with: pip install Pillow")


ROOT       = Path(__file__).resolve().parent.parent
DINO_SRC   = ROOT / "dino.png"
CACTUS_SRC = ROOT / "cactus.png"
DST        = ROOT / "sprites.py"

DINO_H     = 22
CACT_S_H   = 14
CACT_L_H   = 16


def to_mono(path, target_h):
    im = Image.open(path).convert("LA")
    bbox = im.getbbox()
    if bbox:
        im = im.crop(bbox)
    w, h = im.size
    target_w = max(1, round(w * target_h / h))
    im = im.resize((target_w, target_h), Image.LANCZOS)
    rows = []
    for y in range(target_h):
        row = []
        for x in range(target_w):
            l, a = im.getpixel((x, y))
            row.append(1 if (a > 128 and l < 128) else 0)
        rows.append(row)
    return target_w, target_h, rows


def derive_run_b(a):
    # Split the leg region (bottom ~20% of rows) into left/right by the
    # X-centroid of lit pixels, then shift the LEFT-side leg columns up
    # one row. Reads as a mid-stride pose without any hand-tuning.
    h = len(a)
    w = len(a[0])
    leg_rows = max(2, h // 5)
    y0 = h - leg_rows
    xs = [x for y in range(y0, h) for x in range(w) if a[y][x]]
    if not xs:
        return [row[:] for row in a]
    split = sum(xs) // len(xs)
    b = [row[:] for row in a]
    for x in range(split):
        for y in range(y0, h - 1):
            b[y][x] = a[y + 1][x]
        b[h - 1][x] = 0
    return b


def pack_hlsb(rows):
    h = len(rows)
    w = len(rows[0])
    row_bytes = (w + 7) // 8
    buf = bytearray(row_bytes * h)
    for y, row in enumerate(rows):
        for x, bit in enumerate(row):
            if bit:
                buf[y * row_bytes + x // 8] |= 0x80 >> (x % 8)
    return buf


def _emit_bytes(name, buf):
    hexs = ["0x%02X" % b for b in buf]
    lines = []
    for i in range(0, len(hexs), 12):
        lines.append("    " + ", ".join(hexs[i:i + 12]) + ",")
    return "%s = bytes((\n%s\n))" % (name, "\n".join(lines))


def _preview(name, rows):
    print("\n%s:" % name)
    for row in rows:
        print("  " + "".join("#" if v else "." for v in row))


def main():
    if not DINO_SRC.exists():
        sys.exit("dino.png not found at %s" % DINO_SRC)
    if not CACTUS_SRC.exists():
        sys.exit("cactus.png not found at %s" % CACTUS_SRC)

    dw, dh, da = to_mono(DINO_SRC, DINO_H)
    db = derive_run_b(da)
    sw, sh, sa = to_mono(CACTUS_SRC, CACT_S_H)
    lw, lh, la = to_mono(CACTUS_SRC, CACT_L_H)

    parts = [
        "# Auto-generated by tools/build_sprites.py from dino.png + cactus.png.",
        "# Do not edit by hand — regenerate with:",
        "#     python3 tools/build_sprites.py",
        "",
        "DINO_W = %d" % dw,
        "DINO_H = %d" % dh,
        "",
        _emit_bytes("DINO_A", pack_hlsb(da)),
        "",
        _emit_bytes("DINO_B", pack_hlsb(db)),
        "",
        "CACT_S_W = %d" % sw,
        "CACT_S_H = %d" % sh,
        "",
        _emit_bytes("CACT_S", pack_hlsb(sa)),
        "",
        "CACT_L_W = %d" % lw,
        "CACT_L_H = %d" % lh,
        "",
        _emit_bytes("CACT_L", pack_hlsb(la)),
        "",
    ]
    DST.write_text("\n".join(parts))
    print("wrote %s: dino %dx%d, cactus %dx%d + %dx%d"
          % (DST.name, dw, dh, sw, sh, lw, lh))

    _preview("dino frame A", da)
    _preview("dino frame B", db)
    _preview("cactus small", sa)
    _preview("cactus large", la)


if __name__ == "__main__":
    main()
