"""Convert a TTF into a MicroPython bitmap-font module.

Output format (per font module):

    HEIGHT = <int>                     # pixel height of every glyph
    _FONT = { ch: (width, bytes), ... }  # width in px, MONO_HLSB rows

    def get_ch(c): return _FONT.get(c, _FONT[' '])

Each glyph's bytes are `ceil(width/8) * HEIGHT` bytes of MONO_HLSB
(same convention as clipart.py). This runs on the host (CPython + Pillow),
not on the Pico. Re-run it to regenerate a font at a different size.

    python3 tools/build_font.py fonts/arial.ttf arial 24
"""

import os
import sys
from PIL import Image, ImageDraw, ImageFont


FONTS_DIR = os.path.join(os.path.dirname(__file__), "..", "fonts")


def rasterize(ttf_path, size, chars):
    font = ImageFont.truetype(ttf_path, size)
    ascent, descent = font.getmetrics()
    height = ascent + descent
    glyphs = {}
    for ch in chars:
        # Bounding box relative to the origin so we know real advance width.
        left, top, right, bottom = font.getbbox(ch)
        width = max(right, 1)  # keep at least 1px so space renders as a gap
        img = Image.new("1", (width, height), 0)
        ImageDraw.Draw(img).text((0, 0), ch, font=font, fill=1)
        row_bytes = (width + 7) // 8
        packed = bytearray(row_bytes * height)
        px = img.load()
        for y in range(height):
            for x in range(width):
                if px[x, y]:
                    packed[y * row_bytes + (x >> 3)] |= 0x80 >> (x & 7)
        glyphs[ch] = (width, bytes(packed))
    return height, glyphs


def emit(module_path, name, height, glyphs):
    lines = [
        f'"""{name}: generated by tools/build_font.py — do not edit by hand."""',
        "",
        f"HEIGHT = {height}",
        "",
        "_FONT = {",
    ]
    for ch in sorted(glyphs):
        w, data = glyphs[ch]
        lines.append(f"    {ch!r}: ({w}, {bytes(data)!r}),")
    lines += [
        "}",
        "",
        "",
        "def get_ch(c):",
        "    return _FONT.get(c, _FONT[' '])",
        "",
    ]
    with open(module_path, "w") as f:
        f.write("\n".join(lines))


def main():
    if len(sys.argv) != 4:
        print("usage: build_font.py <ttf> <name> <size>", file=sys.stderr)
        sys.exit(2)
    ttf, name, size = sys.argv[1], sys.argv[2], int(sys.argv[3])
    chars = [chr(c) for c in range(0x20, 0x7F)]  # printable ASCII
    height, glyphs = rasterize(ttf, size, chars)
    out = os.path.normpath(os.path.join(FONTS_DIR, f"{name}.py"))
    emit(out, name, height, glyphs)
    total = sum(len(d) for _, d in glyphs.values())
    print(f"{out}: {len(glyphs)} glyphs, height={height}, {total} bytes of bitmap")


if __name__ == "__main__":
    main()
